# Generated by Django 4.2.24 on 2025-11-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_doctor',
            name='password',
            field=models.CharField(default='password123', max_length=100),
        ),
        migrations.AddField(
            model_name='create_patient',
            name='password',
            field=models.CharField(default='password123', max_length=100),
        ),
    ]
