# Generated by Django 4.2.24 on 2025-12-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_patient',
            name='status',
            field=models.CharField(default='Admitted', max_length=20),
        ),
    ]
