# Generated by Django 4.2.24 on 2025-12-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_create_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_patient',
            name='status_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
