# Generated by Django 4.2.24 on 2025-12-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_create_patient_status_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_doctor',
            name='doc_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
